### ISSUE TITLE
it seems this addon stop working

### ISSUE THREAD

**Issue by yichunzhao** [markathomas/LocationTextField#12]
in Vaadin 8, the location completion stop working; actually when input an address, it is in an idle state.

**Comment by markathomas** [comment]
More than likely you're using the OpenStreetMap implementation and they've changed their URL again.  I don't have time to look into it it currently but PRs are welcome.

**Comment by yichunzhao** [comment]
Thanks for the reply; it is the google instance.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by markathomas** [comment]
It appears the API key is now required by Google.  I'll add an option for this.

**Comment by markathomas** [comment]
I have uploaded 3.0.2 which allows the configuration of the API key.
