### ISSUE TITLE
Widgetset does not contain implementation

### ISSUE THREAD

**Issue by Svalorzen** [markathomas/LocationTextField#2]
When using this addon I get this message:

"Widgetset does not contain implementation for org.vaadin.addons.locationtextfield.LocationTextField. Check its @ClientWidget mapping, widgetsets GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to add-on instructions. Unrendered UIDL:
-Unrendered UIDL
-org.vaadin.addons.locationtextfield.LocationTextField(NO CLIENT IMPLEMENTATION FOUND) id=PID2 width=100.0% immediate=true caption=Address: pagelength=10 filteringmode=0 totalitems=0 textChanged=true iem=LAZY iet=1000 eke=true
-variables
selected=
filter=
page=0
ltfFilter=
-options"

I'm using a ton of other addons, and they are all working correctly.

I'm using Eclipse, if this can be useful.

On a side note, I've also had to manually add  the json/slf4j jars to my widgetset, as I could not make the addon work as a standalone.

**Comment by webshopboys** [comment]
Hi, I had this error and checked jar. I used invalid inherits found from web.
<inherits name="org.vaadin.teemu.switchui.SwitchComponentWidgetset" />
But the xml in 1.0.1 jar containst widgetset package so I changed inherits to 
<inherits name="org.vaadin.teemu.switchui.widgetset.SwitchComponentWidgetset" />
and it works well.
BR Karl
