### ISSUE TITLE
Problem with css

### ISSUE THREAD

**Issue by chiccorusso** [markathomas/LocationTextField#5]
HI!
Thank-you for you work.

But we have a problem with the styles: the LocationTextFieldWidgetset imports the Standard themes from GWT, to use its styles in the popup.

But this breaks the whole theme of our application: we use Valo, and including the LocationTextFieldWidgetset the Lato font got replaced with Arial (provided by Standard).
We had to replace the LocationTextFieldWidgetset with another version that does not use Standard.

**Comment by markathomas** [comment]
Thanks for the report. i'll take care of that now

**Comment by markathomas** [comment]
Fixed in 2.1.1
