### ISSUE TITLE
.getText() and null values

### ISSUE THREAD

**Issue by evanzel** [markathomas/LocationTextField#6]
Hi,
It seems the .getText() will not return the displayed text in the widget if that has a length less than the MinimumQueryCharacters. In that case it will return the previous value which is not nice.
That presents a problem since I can’t know if the user has updated the LocationTextField with a null value.
Thanks for the effort.

**Comment by markathomas** [comment]
Please try out 2.1.2 as it should do what you are wanting now.  If not please re-open the issue.  I'd appreciate your vote on the add-on as well.

**Comment by evanzel** [comment]
With 2.1.2, .getText() will now return text with length less than MinimumQueryCharacters, but still
it won't return a null value if the user deletes all input which is the important issue here.

**Comment by markathomas** [comment]
that's the behavior of TextField; not the addon.  do you have setNullRepresentation("") on per chance?  you can check for getText().isEmpty()

**Comment by evanzel** [comment]
I don't think that is the behaviour of TextField or rather I did not describe it properly; I wrote null meaning empty.
If you would replace the init code in the locationtextfield-demo with the following I believe it will be more apparent

[CheckingLTF.txt](https://github.com/markathomas/LocationTextField/files/131969/CheckingLTF.txt)

**Comment by markathomas** [comment]
sorry, i misspoke.  LocationTextField extends Abstractfield in the Vaadin 7 version.  i think i understand your concern and i'll have another look at it

**Comment by markathomas** [comment]
issue is with GWT code.  it calls a different method if text is empty which by default does nothing.  fixing

**Comment by markathomas** [comment]
ok, 2.1.3 should fix your issue.  please test and let me know

**Comment by evanzel** [comment]
This fixes the issue, thanks.

**Comment by markathomas** [comment]
great. please rate the add-on if you have time.  thanks!
